extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 2018

env:
  node: true
  mocha: true

rules:
  comma-style: error
  consistent-this:
    - error
    - _this
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator: 2
  keyword-spacing: error
  no-multi-spaces: off
  no-spaced-func: error
  no-trailing-spaces: error
  quotes:
    - error
    - single
  semi:
    - error
    - never
  curly:
    - error
  prefer-arrow-callback: error
  space-before-blocks: error
  space-before-function-paren:
    - 1
    - anonymous: always
      named: never
  space-infix-ops: error
  space-unary-ops: error
  no-console: off
  no-return-await: error
  eqeqeq: error
